# Generated by Django 6.0.7 on 2026-08-02 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linq', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='linqmessage',
            name='is_valid_list',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='linqmessage',
            name='provider_message_id',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='linqmessage',
            name='reply_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='linqmessage',
            name='reply_text',
            field=models.TextField(blank=True),
        ),
    ]
