# Generated by Django 6.0.7 on 2026-08-02 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linq', '0002_linqmessage_is_valid_list_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinqConversationState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_number', models.CharField(max_length=50, unique=True)),
                ('pending_product', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PriceTrackerItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_number', models.CharField(max_length=50)),
                ('product_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('owner_number', 'product_name'), name='unique_price_tracker_item_per_owner')],
            },
        ),
    ]
