# Generated by Django 6.0.7 on 2026-08-02 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linq', '0003_linqconversationstate_pricetrackeritem'),
    ]

    operations = [
        migrations.AddField(
            model_name='linqconversationstate',
            name='confirmation_step',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
