# Generated by Django 6.0.7 on 2026-08-02 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linq', '0004_linqconversationstate_confirmation_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='linqmessage',
            name='chat_id',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
