# Generated by Django 6.0.7 on 2026-08-02 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linq', '0005_linqmessage_chat_id'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pricetrackeritem',
            name='unique_price_tracker_item_per_owner',
        ),
        migrations.AddField(
            model_name='linqconversationstate',
            name='answers',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='linqconversationstate',
            name='candidate',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='linqconversationstate',
            name='category',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='linqconversationstate',
            name='questions',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='linqconversationstate',
            name='stage',
            field=models.CharField(default='idle', max_length=40),
        ),
        migrations.AddField(
            model_name='pricetrackeritem',
            name='availability',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='pricetrackeritem',
            name='brand',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='pricetrackeritem',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='pricetrackeritem',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='pricetrackeritem',
            name='merchant',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='pricetrackeritem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='pricetrackeritem',
            name='price_change',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='pricetrackeritem',
            name='product_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pricetrackeritem',
            name='product_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='pricetrackeritem',
            name='source_mcp',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='pricetrackeritem',
            name='variant',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddConstraint(
            model_name='pricetrackeritem',
            constraint=models.UniqueConstraint(condition=models.Q(('product_id__isnull', False)), fields=('owner_number', 'product_id'), name='unique_price_tracker_product_per_owner'),
        ),
    ]
