# Generated by Django 6.0.7 on 2026-08-02 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linq', '0006_remove_pricetrackeritem_unique_price_tracker_item_per_owner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_number', models.CharField(max_length=50)),
                ('product_id', models.CharField(max_length=255)),
                ('product_name', models.CharField(max_length=255)),
                ('brand', models.CharField(blank=True, max_length=255)),
                ('variant', models.CharField(blank=True, max_length=255)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('merchant', models.CharField(blank=True, max_length=255)),
                ('availability', models.CharField(blank=True, max_length=255)),
                ('image_url', models.URLField(blank=True)),
                ('product_url', models.URLField(blank=True)),
                ('source', models.CharField(blank=True, max_length=255)),
                ('price_change', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('owner_number', 'product_id'), name='unique_watchlist_product_per_owner')],
            },
        ),
    ]
